#Header h
#  uint32 seq
 # time stamp
  #string frame_id
string h

    float64 x3
    float64 y3
    float64 z3
  
    float64 qx3
    float64 qy3
    float64 qz3
    float64 qw3
    
    float64 x1
    float64 y1
    float64 z1
  
    float64 qx1
    float64 qy1
    float64 qz1
    float64 qw1

    float64 x2
    float64 y2
    float64 z2
  
    float64 qx2
    float64 qy2
    float64 qz2
    float64 qw2
 float64 x4
    float64 y4
    float64 z4
  
    float64 qx4
    float64 qy4
    float64 qz4
    float64 qw4
